#!/bin/bash

# Script to list PCI devices for SR-IOV

# get_net_pcie_slot_name $1 $2
#   argument $1 is the network device name
#   argument $2 is the virtual function number
get_net_pcie_slot_name () {
  if [ -z "$2" ]
  then
    # Get the slot name of the PD (physical device)
    source /sys/class/net/$1/device/uevent

  else
    # Get the slot name of the VD (virtual device)
    source /sys/class/net/$1/device/virtfn${2}/uevent

  fi

  echo $PCI_SLOT_NAME
}


# Specify the network device names here
NET_DEV_0=enlan2
NET_DEV_1=enlan3

# Specify the total number of virtual functions to be configured here
NET_DEV_0_NUMVFS=12
NET_DEV_1_NUMVFS=12

echo "step 1: list virutal function PCI-E addresses"
echo $NET_DEV_0
for (( i=0; i<$NET_DEV_0_NUMVFS; i++ ))
do
  #echo "welccome $i"
  echo $NET_DEV_0 VF$i $(get_net_pcie_slot_name $NET_DEV_0 $i)

done

echo $NET_DEV_1
for (( i=0; i<$NET_DEV_1_NUMVFS; i++ ))
do
  #echo "welccome $i"
  echo $NET_DEV_1 VF$i $(get_net_pcie_slot_name $NET_DEV_1 $i)

done
