#!/bin/bash

# Script to enable and set-up SR-IOV for net devices on boot

# get_net_pcie_slot_name $1 $2
#   argument $1 is the network device name
#   argument $2 is the virtual function number
get_net_pcie_slot_name () {
  if [ -z "$2" ]
  then
    # Get the slot name of the PD (physical device)
    source /sys/class/net/$1/device/uevent

  else
    # Get the slot name of the VD (virtual device)
    source /sys/class/net/$1/device/virtfn${2}/uevent

  fi

  echo $PCI_SLOT_NAME
}


# Specify the network device names here
NET_DEV_0=enlan2
NET_DEV_1=enlan3

# Specify the total number of virtual functions to be configured here
NET_DEV_0_NUMVFS=12
NET_DEV_1_NUMVFS=12

# Specify the driver to use when activating an interface on the host
NET_DEV_0_DRV=iavf
NET_DEV_1_DRV=iavf


echo "step 1: disable auto mount"
echo 0 > /sys/class/net/$NET_DEV_0/device/sriov_drivers_autoprobe
echo 0 > /sys/class/net/$NET_DEV_1/device/sriov_drivers_autoprobe

echo "step 2: make sure all virtual functions are deleted"
echo 0 > /sys/class/net/$NET_DEV_0/device/sriov_numvfs
echo 0 > /sys/class/net/$NET_DEV_1/device/sriov_numvfs

echo "step 3: create the virtual functions"
echo $NET_DEV_0_NUMVFS > /sys/class/net/$NET_DEV_0/device/sriov_numvfs
echo $NET_DEV_1_NUMVFS > /sys/class/net/$NET_DEV_1/device/sriov_numvfs

echo "step 4: re-enable auto mount"
echo 1 > /sys/class/net/$NET_DEV_0/device/sriov_drivers_autoprobe
echo 1 > /sys/class/net/$NET_DEV_1/device/sriov_drivers_autoprobe

echo "step 5: set mac addresses (hint: use /etc/systemd/network/*.link to set names)"
#ip link set $NET_DEV_0 vf 0 mac 3a:57:61:0e:eb:00
ip link set $NET_DEV_0 vf 1 mac 3a:57:61:0e:eb:01
ip link set $NET_DEV_0 vf 2 mac 3a:57:61:0e:eb:02
ip link set $NET_DEV_0 vf 3 mac 3a:57:61:0e:eb:03
ip link set $NET_DEV_0 vf 4 mac 3a:57:61:0e:eb:04
ip link set $NET_DEV_0 vf 5 mac 3a:57:61:0e:eb:05
ip link set $NET_DEV_0 vf 6 mac 3a:57:61:0e:eb:06
ip link set $NET_DEV_0 vf 7 mac 3a:57:61:0e:eb:07
ip link set $NET_DEV_0 vf 8 mac 3a:57:61:0e:eb:08
ip link set $NET_DEV_0 vf 9 mac 3a:57:61:0e:eb:09
ip link set $NET_DEV_0 vf 10 mac 3a:57:61:0e:eb:0a
ip link set $NET_DEV_0 vf 11 mac 3a:57:61:0e:eb:0b

#ip link set $NET_DEV_1 vf 0 mac 3a:57:61:0e:ec:00
ip link set $NET_DEV_1 vf 1 mac 3a:57:61:0e:ec:01
ip link set $NET_DEV_1 vf 2 mac 3a:57:61:0e:ec:02
ip link set $NET_DEV_1 vf 3 mac 3a:57:61:0e:ec:03
ip link set $NET_DEV_1 vf 4 mac 3a:57:61:0e:ec:04
ip link set $NET_DEV_1 vf 5 mac 3a:57:61:0e:ec:05
ip link set $NET_DEV_1 vf 6 mac 3a:57:61:0e:ec:06
ip link set $NET_DEV_1 vf 7 mac 3a:57:61:0e:ec:07
ip link set $NET_DEV_1 vf 8 mac 3a:57:61:0e:ec:08
ip link set $NET_DEV_1 vf 9 mac 3a:57:61:0e:ec:09
ip link set $NET_DEV_1 vf 10 mac 3a:57:61:0e:ec:0a
ip link set $NET_DEV_1 vf 11 mac 3a:57:61:0e:ec:0b

echo "step 6: set vlans"
# do not use vf0
ip link set dev ${NET_DEV_0} vf 10 vlan 0
ip link set dev ${NET_DEV_0} vf 11 vlan 0

# do not use vf0
ip link set dev ${NET_DEV_1} vf 6 vlan 4 # docker-001 network interface - fix address
ip link set dev ${NET_DEV_1} vf 7 vlan 0 # docker-001 - nas interface - leave as dhcp for now
ip link set dev ${NET_DEV_1} vf 8 vlan 2 # proxmox-backup-server - trusted network interface - fix address
ip link set dev ${NET_DEV_1} vf 9 vlan 0 # proxmox-backup-server - nas interface - leave as dhcp for now
ip link set dev ${NET_DEV_1} vf 10 vlan 0
ip link set dev ${NET_DEV_1} vf 11 vlan 0

echo "step 7: activate drivers for specific interfaces"
echo $(get_net_pcie_slot_name $NET_DEV_0 10) > /sys/bus/pci/drivers/$NET_DEV_0_DRV/bind
echo $(get_net_pcie_slot_name $NET_DEV_0 11) > /sys/bus/pci/drivers/$NET_DEV_0_DRV/bind

echo $(get_net_pcie_slot_name $NET_DEV_1 10) > /sys/bus/pci/drivers/$NET_DEV_1_DRV/bind
echo $(get_net_pcie_slot_name $NET_DEV_1 11) > /sys/bus/pci/drivers/$NET_DEV_1_DRV/bind

echo "step 8: rename activated interfaces"
echo "systemd is used to rename interfaces - refer under /etc/systemd/network/*.link"
